### ISSUE TITLE
A question about knowledge distillation

### ISSUE THREAD

**Issue by littleKaa** [lhyfst/knowledge-distillation-papers#1]
Hi, 

Thank you for the paper list, It is very helpful.

May I ask a question abut knowledge distillation？

Most of  the papers(or all of the papers) listed are about transfer knowledge from a complex network to a simplified network on the same training dataset,
 is there any research about transfer knowledge from  meaningful features to less-meaningful features?

Sincerely.
Thank you.

**Comment by lhyfst** [comment]
Hello!

Your idea sounds great! As far as I know, there is no paper like what you said. I did read one paper called [Feature Distillation: DNN-Oriented JPEG Compression Against Adversarial Examples](https://arxiv.org/pdf/1803.05787), but the paper's idea and goal are not like yours, even do not have strong relationships with knowledge distillation.

However, I have not searched papers on your idea especially. So you had better check it by yourself. BTW, if you find one, please let me know.

I am wondering how you plan to implement your idea in detail. If you don't mind, I am glad to know it.

Good luck! Happy to read your paper early!

**Comment by littleKaa** [comment]
Thank you for answering this question. 

I haven't found any paper about this problem either. 
You see, In many cold-start problem, we don't have meaningful feautures. Models based on less-meaningful features usually achieve a bad result.

It's just a fancy idea. And I am new in knowledge distillation. 
May I ask a question about  why knowledge distillation works for transfer knowledge from a complex network to a simplified one?

If we know this reason, maybe we can infer whether transfer from meaningful features to less-meaningful features would work.

Looking forward for your reply.
Thank You

**Comment by lhyfst** [comment]
For the question why knowledge distillation works, please refer early papers in my list.
